name: "Build Docker Image"

on:
  push:
    branches:
      - "master"
      - "dev"

  workflow_dispatch:
    inputs:
      canarytokens-docker-branch:
        description: "Branch of the canarytokens-docker repo to pull for build. Defaults to master"
        required: false

jobs:


  dev-deploy:
    runs-on: [self-hosted, dev]
    steps:
      - name: Deploy to dev machine
        run: |
          echo "I was here " > /tmp/test.txt


  staging-deploy:
    if: github.repository == 'thinkst/canarytokens' && github.ref == 'refs/heads/master'
    runs-on: [self-hosted, staging]
    needs: build
    steps:
      - name: Deploy to staging machine
        run: |
          cd /home/ubuntu/canarytokens-scripts/
          ./canarytokensdb_s3backup.sh

          cd /home/ubuntu/canarytokens-docker
          sed "s/thinkst\/canarytokens:dev/thinkst\/canarytokens:${GITHUB_REF##*/}/g" docker-compose-letsencrypt.yml.tpl > docker-compose-letsencrypt.yml
          sed -i'' "s/CANARY_DEV_BUILD_ID=.*/CANARY_DEV_BUILD_ID=${GITHUB_SHA:0:8}/" frontend.env
          sudo docker pull thinkst/canarytokens:${GITHUB_REF##*/}
          sudo docker-compose -f docker-compose-letsencrypt.yml pull
          sudo docker-compose -f docker-compose-letsencrypt.yml down
          sudo docker-compose -f docker-compose-letsencrypt.yml up -d
          sudo docker system prune -f -a
